# Twitter keys/tokens - obtain yours from https://developer.twitter.com/en/apps
'API_KEY': 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'
'API_SECRET_KEY': 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'
'ACCESS_TOKEN': 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'
'ACCESS_TOKEN_SECRET': 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'
